#!/bin/sh

set system.system.timezone='CST-8'
	set system.system.zonename='Asia/Shanghai'
	uci commit system

	uci set luci.main.lang=zh_cn
	uci commit luci


#        uci set network.globals.ula_prefix='2fff::/64'
#        uci set network.lan.ip6assign='64'
        uci set network.lan.ipaddr='10.10.10.10'
        uci set network.lan.netmask='255.255.255.0'
#        uci set network.lan.gateway='10.10.10.10'
#        uci set network.wan6.peerdns='0'
#        uci set network.wan6.dns='2001:4860:4860::8888'
#        uci set network.wan.ipv6=1
        uci commit network

        uci set dhcp.lan.ra='server'
        uci set dhcp.lan.dhcpv6='server'     
        uci set dhcp.lan.ra_management='1'
        uci set dhcp.lan.ra_default='1'
        uci set dhcp.lan.leasetime='30m'
        uci set dhcp.lan.start='10'
#        uci set dhcp.lan.dhcp_option='6,10.10.10.28'
        uci commit dhcp

        wifi down 
        wifi up

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="zh_cn"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

ed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

exit 0
