#!/bin/sh
# Include both data packages and enable scheduled updates after installation.
[ -f /etc/config/passwall ] || exit 0
uci -q get passwall.@global_rules[0] >/dev/null || uci add passwall global_rules >/dev/null
uci set passwall.@global_rules[0].geoip_update='1'
uci set passwall.@global_rules[0].geosite_update='1'
uci set passwall.@global_rules[0].v2ray_location_asset='/usr/share/v2ray/'
uci set passwall.@global_rules[0].auto_update='1'
uci set passwall.@global_rules[0].week_update='0'
uci set passwall.@global_rules[0].time_update='4'
uci commit passwall
exit 0
