#!/bin/sh
# MosDNS DNS settings, applied only on fresh installations.
set -eu

case "$(cat /tmp/sysinfo/board_name)" in
    nokia,xg-040g-md|nokia,xg-040g-md-ubi) ;;
    *) exit 0 ;;
esac
if [ -f /sysupgrade.tgz ] || [ -f /tmp/sysupgrade.tar ] ||
   [ "$(uci -q get mosdns.config.xg040gmd_dns_defaults || true)" = 1 ]; then
    exit 0
fi
uci -q get mosdns.config >/dev/null || exit 1

uci set mosdns.config.enabled=1
uci set mosdns.config.listen_port=6053
uci set mosdns.config.redirect=1
uci set mosdns.config.local_dns_redirect=0
uci set mosdns.config.prefer_ipv4=1
uci set mosdns.config.prefer_ipv4_cn=1
uci set mosdns.config.cache=1
uci set mosdns.config.cache_size=4096
uci set mosdns.config.lazy_cache_ttl=3600
uci set mosdns.config.prefetch=1
uci set mosdns.config.concurrent=2
uci set mosdns.config.idle_timeout=120
uci set mosdns.config.bootstrap_dns=223.5.5.5
uci set mosdns.config.custom_local_dns=1
uci set mosdns.config.reject_type65=1
uci set mosdns.config.stats_capacity=500
uci -q delete mosdns.config.local_dns || true
uci add_list mosdns.config.local_dns='https://223.5.5.5/dns-query'
uci add_list mosdns.config.local_dns='https://119.29.29.29/dns-query'
uci -q delete mosdns.config.remote_dns || true
uci add_list mosdns.config.remote_dns='https://1.1.1.1/dns-query'
uci add_list mosdns.config.remote_dns='https://8.8.8.8/dns-query'

uci -q delete dhcp.@dnsmasq[0].server || true
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#6053'
uci set dhcp.@dnsmasq[0].noresolv=1
# The LuCI redirect option also sets this to zero; cache lives in MosDNS.
uci set dhcp.@dnsmasq[0].cachesize=0
uci set mosdns.config.xg040gmd_dns_defaults=1
uci commit mosdns
uci commit dhcp
exit 0
