#!/bin/sh /etc/rc.common
START=99
STOP=80
USE_PROCD=1
start_service() {
    /usr/sbin/haproxy -c -q -f /etc/codex-proxy/haproxy.cfg || return 1
    procd_open_instance
    procd_set_param command /usr/sbin/haproxy -W -db -f /etc/codex-proxy/haproxy.cfg
    procd_set_param respawn
    procd_set_param file /etc/codex-proxy/haproxy.cfg
    procd_close_instance
}
